services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    # Este comando obliga al Master a quedarse encendido
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ${SPARK_DATA_PATH}:/opt/spark/data

  spark-worker-1:
    image: apache/spark:3.5.0
    container_name: spark-worker-1
    # Este comando conecta al Worker con el Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
    volumes:
      - ${SPARK_DATA_PATH}:/opt/spark/data
    depends_on:
      - spark-master

  spark-worker-2:
    image: apache/spark:3.5.0
    container_name: spark-worker-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
    volumes:
      - ${SPARK_DATA_PATH}:/opt/spark/data
    depends_on:
      - spark-master

  project-dashboard:
    image: nginx:alpine
    container_name: project-dashboard
    ports:
      - "8081:80"
    volumes:
      - ./www:/usr/share/nginx/html
